### ISSUE TITLE
App notifications bottom margin

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#109]
In fact i think it related to all notifications.

If Notification component doesn't have message (only title) there is a unnecessary bottom padding

Next thing is that notifications should have border-top (starting from second child of his type) otherwise they looks like one notification

Unnecessary margin examples:
![screen shot 2018-10-02 at 14 01 03](https://user-images.githubusercontent.com/3435913/46347401-ae110d00-c64b-11e8-807c-584a3fe0b567.png)

![screen shot 2018-10-02 at 14 02 08](https://user-images.githubusercontent.com/3435913/46347439-d0a32600-c64b-11e8-80b1-8c7a9dca12b6.png)

Working example of AppNotifications are in branch/PR:
https://github.com/trezor/trezor-wallet/pull/108

**Comment by szymonlesisz** [comment]
And also, notification title is not vertically centered with icon (few pixels from top is missing)

**Comment by vladimirvolek** [comment]
also they are still not responsive.

**Comment by vladimirvolek** [comment]
also group notifications

![image](https://user-images.githubusercontent.com/3112191/46746460-67f12480-ccaf-11e8-9645-cadb10966f4d.png)
