### ISSUE TITLE
Implement review + click through and check Accounts pages are ok

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-wallet#119]
from https://github.com/trezor/trezor-wallet/pull/85

- put back urls in config - https://github.com/trezor/trezor-wallet/pull/121
- content to fragment - https://github.com/trezor/trezor-wallet/pull/126
- fonts 404 https://github.com/trezor/trezor-wallet/pull/122
- tooltips - padding, styles, buttons - https://github.com/trezor/trezor-wallet/pull/126

**Comment by szymonlesisz** [comment]
+ make sure that renamed files didn't changed on master before this merge:

modals/pin/Pin/components/Button/index.js
/modals/pin/Pin/components/Input/index.js
