### ISSUE TITLE
css: Line spacing in modal paragraphs

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#138]
line spacing looks broken on multiple places. example:
![screen shot 2018-10-09 at 10 13 03](https://user-images.githubusercontent.com/3435913/46655540-2b88d000-cbac-11e8-90c5-0ccac997a272.png)

**Comment by vladimirvolek** [comment]
will be fixed in https://github.com/trezor/trezor-wallet/issues/139
