### ISSUE TITLE
Fix WalletType modal

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#139]
current:
![screen shot 2018-10-09 at 10 13 28](https://user-images.githubusercontent.com/3435913/46655601-612db900-cbac-11e8-8c64-8d9cd93adb91.png)

layout:
https://projects.invisionapp.com/d/main#/console/13218523/323932928/inspect

**Comment by vladimirvolek** [comment]
+ line spacing in all modals
