### ISSUE TITLE
Replace the links to the old documentation by the new ones 

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-wallet#142]
Similar to this issue in the old wallet wallet.trezor.io
https://github.com/satoshilabs/trezor-qa/issues/49

Some links still lead to an old-outdated documentation (doc.satoshilabs.com). 

1. Docs in the header
![screenshot from 2018-10-09 11-58-34](https://user-images.githubusercontent.com/31442634/46662089-ca1c2d80-cbba-11e8-8329-e60380552c16.png)

2. Learn more
![screenshot from 2018-10-09 12-00-33](https://user-images.githubusercontent.com/31442634/46662164-fcc62600-cbba-11e8-9bb0-992d14e56eca.png)

**Comment by szymonlesisz** [comment]
fixed

**Comment by pankrats** [comment]
Docs link in the header still leads to https://doc.satoshilabs.com/trezor-user/

On the updated old wallet version the link is renamed to "Wiki" and leads to https://wiki.trezor.io/
<img width="1059" alt="screen shot 2018-10-10 at 11 12 46" src="https://user-images.githubusercontent.com/31442634/46725946-935b1b80-cc7d-11e8-9271-cd209b1f2352.png">
