### ISSUE TITLE
css: Action notification on LadingPage

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#146]
they are a little bit squashed

![screen shot 2018-10-09 at 13 31 08](https://user-images.githubusercontent.com/3435913/46666753-ca6ef580-cbc7-11e8-8bce-cee963710bc1.png)

**Comment by vladimirvolek** [comment]
![image](https://user-images.githubusercontent.com/3112191/46671089-28093f00-cbd4-11e8-8ccf-36499c0233f1.png)
