### ISSUE TITLE
Implement Ripple

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-wallet#151]
As a proof of blockchain-link concept, implement Ripple without a need of blockbook backend.

The most straightforward way is probably https://github.com/ripple/ripple-lib.

**Comment by okipol88** [comment]
Could you elaborate on the blockchain-link concept? Any docs?

**Comment by prusnak** [comment]
blockchain-link is a Javascript connector that connects to an arbitrary backend and provides API for our webwallet. It's a work in progress.

**Comment by okipol88** [comment]
I cannot find it in the Trezor repository. Is it not public yet?

**Comment by prusnak** [comment]
Correct

**Comment by vladimirvolek** [comment]
Ripple is now implemented -> https://beta-wallet.trezor.io/next/
