### ISSUE TITLE
Link "Try installing the TREZOR Bridge." does not work

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-wallet#157]
Clicking on this link does nothing :(

<img width="561" alt="screen shot 2018-10-10 at 11 24 23" src="https://user-images.githubusercontent.com/31442634/46726683-25afef00-cc7f-11e8-93bd-20f6f1ce80ec.png">

**Comment by vladimirvolek** [comment]
+ refactor all links and use NavLink from react-router-dom
