### ISSUE TITLE
Trezor wallet works in Opera on background

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-wallet#161]
Production version wallet says go to Chrome or Firefox but it asks for PIN code or to remember wallet after disconnected.

![screenshot from 2018-10-10 10-26-08](https://user-images.githubusercontent.com/31506317/46731649-89d8b000-cc8b-11e8-925c-ff3f5b729434.png)
![photo_2018-10-10_12-54-25](https://user-images.githubusercontent.com/31506317/46731683-a248ca80-cc8b-11e8-8356-27739c721ced.jpg)

**Comment by szymonlesisz** [comment]
You are testing "old wallet" (dev.trezor.io/develop/bitcoin)
So report it to proper repo: https://github.com/satoshilabs/mytrezor/issues

This repo is for dev.trezor.io/ethereum only
