### ISSUE TITLE
CoinMarketCap Public API will be taken offline on December 4th, 2018

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#178]
related to https://github.com/satoshilabs/mytrezor/issues/372

**Comment by bobbyong** [comment]
Hi @szymonlesisz , may I suggest you take our API into consideration at https://www.coingecko.com/api

API is public and free to use, no keys needed and with little restriction to throttling.
Suggest you at least give it a try, open to hearing your feedbacks and concerns.

We at CoinGecko are big fans of Trezor

**Comment by okipol88** [comment]
Hi @szymonlesisz,

Coinpaprika is another option:
[Coinpaprika API](https://api.coinpaprika.com/)

Please take it into consideration.

**Comment by szymonlesisz** [comment]
Hi guys,
Thanks for your tips, we're going to work on this from in november and we'll take all options into consideration

**Comment by vladimirvolek** [comment]
> Hi @szymonlesisz , may I suggest you take our API into consideration at https://www.coingecko.com/api
> 
> API is public and free to use, no keys needed and with little restriction to throttling.
> Suggest you at least give it a try, open to hearing your feedbacks and concerns.
> 
> We at CoinGecko are big fans of Trezor

Hey @bobbyong!

We just used your API :)
