### ISSUE TITLE
Refresh at /bridge or /import page redirects to the home page

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-wallet#182]

**Comment by szymonlesisz** [comment]
It's desired behaviour
Router is checking if initial url belongs to "landing page" schema:
https://github.com/trezor/trezor-wallet/blob/master/src/actions/RouterActions.js#L345

We don't want to redirect user to page which is available only on certain conditions (not installed or outdated bridge)

**Comment by vladimirvolek** [comment]
okay :)
