### ISSUE TITLE
Wallet Terms link needs to be updated

### ISSUE THREAD

**Issue by vir-satoshi** [trezor/trezor-wallet#188]
The actual link to Terms on the bottom of the wallet needs to be updated. 

![vir-issue-0024-trezor-wallet-link](https://user-images.githubusercontent.com/37402655/46970713-2fd85000-d0ba-11e8-9303-4d07d2b78803.png)

https://beta-wallet.trezor.io/tos.pdf or the actual link...

**Comment by vladimirvolek** [comment]
The link is depending on environment, in prod there will be https://wallet.trezor.io.
