### ISSUE TITLE
css: switching between Send/Receive on small screens

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#193]
Switching between those two tabs on smaller screens makes TopNavigation items jumping
It's because of Receive page input min-width.

![screen shot 2018-10-16 at 16 22 39](https://user-images.githubusercontent.com/3435913/47023360-d9255180-d15f-11e8-8809-269dbbd8a221.png)
![screen shot 2018-10-16 at 16 22 48](https://user-images.githubusercontent.com/3435913/47023374-dd516f00-d15f-11e8-8fd1-b299b5d2e70a.png)

**Comment by vladimirvolek** [comment]
Can you confirm this is still an issue?

**Comment by szymonlesisz** [comment]
yes, its still there
