### ISSUE TITLE
Export build package from docker

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#203]
To be able to sync files with server we need to add more options to docker build:

1. Add possibility to build custom target: prod/beta/dev in docker
2. Expose builded files, like it's done in old-wallet:
https://github.com/satoshilabs/mytrezor/blob/develop/docker-build/run_inside.sh#L34-L37

**Comment by vladimirvolek** [comment]
resources are now available at gitlab (https://gitlab.corp.sldev.cz/trezor/trezor-wallet/pipelines/372)
