### ISSUE TITLE
Beta/Next ETH Wallet - Advanced option activation breaks the interface

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-wallet#246]
When advanced option isn't active:
![advanced1](https://user-images.githubusercontent.com/37402530/48413379-d78f7f00-e747-11e8-8564-f046f68ba351.png)

When advanced option is activated
![advanced2](https://user-images.githubusercontent.com/37402530/48413383-da8a6f80-e747-11e8-8c6e-adfc88145545.png)

**Comment by slowbackspace** [comment]
Can you still reproduce it?

**Comment by yohaaan** [comment]
Already fixed.

**Comment by vladimirvolek** [comment]
👍
