### ISSUE TITLE
Account transaction history

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#248]
Should be somewhere in summary tab.
Prepare design for Ripple and Ethereum. Mine difference between then is that Ethereum has tokens (and input to add them manually) and ripple doesn't.
Maybe there should be another tab for adding tokens?

**Comment by szymonlesisz** [comment]
also it's related to https://github.com/trezor/trezor-wallet/issues/238

**Comment by fantic** [comment]
<img width="928" alt="snimek obrazovky 2018-11-21 v 13 17 27" src="https://user-images.githubusercontent.com/10602692/48840789-f3ba9e00-ed8f-11e8-9099-3530917479ac.png">
https://invis.io/ZKFL3WLVCH2#/332607553_Ethereum-Wallet-Tokens-01_Copy

**Comment by fantic** [comment]
<img width="771" alt="snimek obrazovky 2018-11-21 v 13 22 06" src="https://user-images.githubusercontent.com/10602692/48840989-72afd680-ed90-11e8-943d-890b420ba529.png">

do we want to make the transaction history same as in the old wallet? or do We want to make the newest and more convenient version but that is not going to be consistent when you will be transferring between wallets.
