### ISSUE TITLE
field size problem in Eth wallet

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-wallet#261]
See attachment.
If you enter ERC20 token name or amount of transferred that's too long it will break page design

![screenshot from 2018-12-05 12-05-08](https://user-images.githubusercontent.com/31506317/49509690-56c72d00-f886-11e8-9c38-47c14251243e.png)
![screenshot from 2018-12-05 12-08-13](https://user-images.githubusercontent.com/31506317/49509735-76f6ec00-f886-11e8-8f8b-369fb828a298.png)

**Comment by slowbackspace** [comment]
I have looked at the issue and there are some weird problems with hidden overflow. I think it is better to first implement responsive design (issue https://github.com/trezor/trezor-wallet/issues/28). That should solve it automatically.
