### ISSUE TITLE
Custom fee doesn't send NAMECOIN transaction

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-wallet#263]
Sending NMC transaction custom fee ends with error /anything below 100 satoshi/

![image_2018-12-05_15-41-51](https://user-images.githubusercontent.com/31506317/49521377-9d784f80-f8a5-11e8-98fe-f53d7e7babe4.png)

**Comment by vladimirvolek** [comment]
Is this somehow related to this wallet?
