### ISSUE TITLE
Bridge download page should link to signature

### ISSUE THREAD

**Issue by jonathancross** [trezor/trezor-wallet#286]
The [Bridge download page](https://wallet.trezor.io/#/bridge) links to the latest version of the bridge, but does not link to the gpg signature for that file.  We should make it as easy as possible for users to verify the integrity of downloaded software.

Options:

1. Add a link to the page pointing to the specific `sig` file needed to verify, eg:
  [trezor-bridge-2.0.25.pkg](https://wallet.trezor.io/data/bridge/latest/trezor-bridge-2.0.25.pkg)
  [trezor-bridge-2.0.25.pkg.asc](https://wallet.trezor.io/data/bridge/latest/trezor-bridge-2.0.25.pkg.asc)

2. Just add a generic link to help people find all downloads, eg:
  "More downloads: [OpenPGP signatures and packages for other platforms](https://wallet.trezor.io/data/bridge/latest/index.html)"

**Comment by szymonlesisz** [comment]
Hi @jonathancross,
Thanks for your feedback, however this repository is a next version of our wallet (currently running on https://beta-wallet.trezor.io/next/#/) and this feature is already implemented here.
Your issue regards stable wallet (running on wallet.trezor.io) so i'm moving it there.
