### ISSUE TITLE
Remove wallet icon for "standart type"

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-wallet#334]
Also add button for switching wallet type to be visible all the time

**Comment by slowbackspace** [comment]
related...
Wouldn't it be better if we renamed "Change wallet type" button to something like "Go to your standard/hidden wallet", based on the wallet type user is currently in? To me, it is easier to understand as I don't have to think what exactly the wallet type is.
 
<img width="331" alt="screenshot 2019-01-15 at 15 50 22" src="https://user-images.githubusercontent.com/6961901/51188137-a6fdca00-18dd-11e9-9bb1-a531ab4a5f99.png">

**Comment by slowbackspace** [comment]
Maybe wallet icon should stay visible and instead we could turn it into a button (with tooltip, https://github.com/trezor/trezor-wallet/issues/318 ) which would open the same dialog as "change wallet type"
