### ISSUE TITLE
Send NaN XRP/ETH

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-wallet#372]
![image](https://user-images.githubusercontent.com/3112191/53026447-3cebbe00-3463-11e9-91de-7ad3a5c9bf0a.png)

**Comment by slowbackspace** [comment]
xrp also affected 
<img width="620" alt="screenshot 2019-02-19 at 18 39 52" src="https://user-images.githubusercontent.com/6961901/53035484-d45a0c80-3475-11e9-9866-144d33d3826f.png">
