### ISSUE TITLE
Verifying address error

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-wallet#377]
See screenshot. tested with new FW 2.1.0
Firefox, nixos, bridge 2.0.25

Verifying address error
Missing at least one required field for Message .EthereumAddress: address

![screenshot_20190220_104251](https://user-images.githubusercontent.com/31506317/53082076-6efd2e80-34fc-11e9-9188-dfe6ed0f5772.png)

**Comment by szymonlesisz** [comment]
should be fixed now (in connect@sisyfos)
