### ISSUE TITLE
Correct text in the Ripple wallet 

### ISSUE THREAD

**Issue by vir-satoshi** [trezor/trezor-wallet#378]
Officially the first Trezor model is called Trezor One. Please correct the text in the Ripple wallet while using Trezor One.

![image](https://user-images.githubusercontent.com/37402655/53086396-51809280-3505-11e9-94fd-7f4405afc7e2.png)

**Comment by vladimirvolek** [comment]
![image](https://user-images.githubusercontent.com/3112191/53087514-acb38480-3507-11e9-8829-1667266abbbc.png)

**Comment by vladimirvolek** [comment]
https://github.com/trezor/trezor-wallet/commit/e9d3f3ff92026812d0a686a198b5510849582c19
