### ISSUE TITLE
Add Tezos to next wallet menu

### ISSUE THREAD

**Issue by vir-satoshi** [trezor/trezor-wallet#429]
We are adding Tezos into the beta wallet with the upcoming 2.1.0 support. It will be fine to implement a link to the next wallet as well.

![tezos-nextwallet](https://user-images.githubusercontent.com/37402655/53743672-a9bb7b00-3e9b-11e9-85ed-aff95d7e6722.png)

![image](https://user-images.githubusercontent.com/37402655/53743899-159de380-3e9c-11e9-8edc-892b896b894a.png)

the link is  : https://wallet.simplestaking.com/tezos/wallet/start

**Comment by vladimirvolek** [comment]
Add to release/1.1.1-beta branch
