### ISSUE TITLE
Dry run - "seed check finished" dialogue when prompted for PIN

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-wallet#440]
TT fw 2.1.0 with PIN set up, any wallet

Wallet displays a "Seed check finished" dialogue just before the dry run starts, when prompted for entering PIN.

![fw 2 1 0](https://user-images.githubusercontent.com/10185314/53886991-96d2b300-4021-11e9-8762-1355c5a85607.jpg)

fw 2.0.8, same step as above
![fw 2 0 8](https://user-images.githubusercontent.com/10185314/53886990-963a1c80-4021-11e9-90c7-2e0c8c244a0a.jpg)

**Comment by slowbackspace** [comment]
This doesn't seem to be related to the next wallet since we don't have any recovery functionality implemented yet.
