### ISSUE TITLE
Paranoid mode switch

### ISSUE THREAD

**Issue by MrMebelMan** [trezor/trezor-wallet#445]
It would be nice to have a possibility to hide account balances with some kind of a switch button.

Privacy maximalists would surely appreciate it!

**Comment by slowbackspace** [comment]
![Screen Recording 2019-03-15 at 10 29 03](https://user-images.githubusercontent.com/6961901/54421948-c4001f00-470d-11e9-9f14-d6719c2dc18e.gif)

What do you think? :)
