### ISSUE TITLE
Address input doesn't handle clipboard actions

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-wallet#477]
Pasted address

![image](https://user-images.githubusercontent.com/3112191/55180026-fe939e00-5188-11e9-9ba3-010b80ce07f3.png)

**Comment by slowbackspace** [comment]
I think it is not related to clipboard actions. input state does not update on the first `input__change/touch` event fired.
<img width="538" alt="Screenshot 2019-03-29 at 09 16 05" src="https://user-images.githubusercontent.com/6961901/55218777-5b339f00-5203-11e9-9e99-6925bac3756f.png">

**Comment by slowbackspace** [comment]
I think it is not related to clipboard actions. input state does not update on the first `input__change/touch` event fired.
<img width="538" alt="Screenshot 2019-03-29 at 09 16 05" src="https://user-images.githubusercontent.com/6961901/55218777-5b339f00-5203-11e9-9e99-6925bac3756f.png">
