### ISSUE TITLE
McAfee flags `mytrezor-archive.tgz` as a JS_Coinminer Trojan

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-wallet#488]
***McAfee Total Protection 16.0 R18*** flags `mytrezor-archive.tgz` as a JS_Coinminer Trojan.

This is likely a false report and should be raised to McAfee to be white-listed.  The source of the alert is the `fastxpub.*.js` file.

The `mytrezor-archive.tgz` from the following 3 URIs were tested:

1. https://old-wallet.trezor.io/data/mytrezor-archive.tgz [FAILED - Miner detected]
2. https://wallet.trezor.io/data/mytrezor-archive.tgz [FAILED - Miner detected]
3. https://beta-wallet.trezor.io/data/mytrezor-archive.tgz [PASSED - no miner detected]

The MD5 checksums for the files as of today are as follows:

```
7d74193ca0bebd9b317a7bf2c8b19dc3 *mytrezor\\old-wallet\\mytrezor-archive.tgz
21c01b0b0e58086983122c85c5d80b02 *mytrezor\\wallet\\mytrezor-archive.tgz
4b930e8eeb6072602147c14c59e7ba9c *mytrezor\\beta-wallet\\mytrezor-archive.tgz
```

Here's [McAfee's Threat Advisory](https://kc.mcafee.com/resources/sites/MCAFEE/content/live/PRODUCT_DOCUMENTATION/27000/PD27447/en_US/McAfee_Labs_Threat_Advisory-JS_Coinminer.pdf) for the alert.

The following is a general reproduction procedure for Linux / Mac users:

1. Install [VirtualBox 16.0](https://www.virtualbox.org/wiki/Downloads)
2. Download Windows 10 Enterprise from [MS Evaluation Center](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise)
3. Create a Windows10x64 VM in VirtualBox to install the ISO into.
4. Install Windows 10 into the VM.
5. Once setup is complete download all three versions of `mytrezor-archive.tgz`
6. Install McAfee Total Protection free trial
7. Scan the `mytrezor-archive.tgz` files with McAfee
8. Note the results.

Here's a command shell walk through as well.

```
# Get run window with [WIN]-R key combo
# Run "cmd.exe"
# Inside cmd.exe issue the following commands
cd "%userprofile%\Downloads"
powershell start-process powershell.exe -verb runas

# A powershell will now be active, in it type the following
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
exit

# Relaunch the powershell
powershell start-process powershell.exe -verb runas

# In the fresh powershell, type the following
cd $env:userprofile\Downloads
choco install -y googlechrome gnuwin32-coreutils.portable 7zip.portable wget python3
start-process chrome https://home.mcafee.com/downloads/oneclicktrial.aspx

# In the chrome window, download the Trial Installer to `Downloads` folder

# Grab the files to test
wget.exe https://old-wallet.trezor.io/data/mytrezor-archive.tgz -P mytrezor\old-wallet
wget.exe https://wallet.trezor.io/data/mytrezor-archive.tgz -P mytrezor\wallet
wget.exe https://beta-wallet.trezor.io/data/mytrezor-archive.tgz -P mytrezor\beta-wallet

# start a new CMD shell
start-process cmd

# In the new CMD shell type the following
for /f %p in ('dir /s/b *.tgz') do @(md5sum "%p") >> md5sum.txt
md5sum.exe --check md5sum.txt
exit

# Back in the powershell issue the following, where [TAB] is for tab completion
Start-Process .\mcafee_trial_setup_[TAB] -verb runas
exit

# Wait for the install to complete
# Back in the original CMD shell type the following
start .
# Right click on `mytrezor` folder and select `Scan`
```

**Comment by brianddk** [comment]
Note that McAfee Endpoint Security v10.5.0 (the licensed enterprise edition) will alert on `beta-wallet\\mytrezor-archive.tgz` even though McAfee Total Protection 16.0 does not.  Whats more, McAfee Endpoint Security will actively block the file in browser cache and could actually effect the functioning of the site for the user.  At least in so much as `fastxpub.*.js` is required for the use of the site to begin with.

**Comment by vladimirvolek** [comment]
Hello @brianddk,
mytrezor is our old wallet, we will investigate this issue there.

Thank you for your report.

**Comment by brianddk** [comment]
> mytrezor is our old wallet, we will investigate this issue there

@vladimirvolek , The [trezor wiki](https://wiki.trezor.io/User_manual:Running_a_local_instance_of_Trezor_Wallet) is still pointing to mytrezor instances linked above.  You will probably want to update the wilki so as not to point to the old wallet any longer.

Also note that ***McAfee Total Protection 16.0*** also alerts off the JS file from `wallet.trezor.io` which I believe is your live production wallet:
```
wget https://wallet.trezor.io/fastxpub.18e2cb2e67ded05fa873d5a93258a58e694d5fe4.js
```

**Comment by vladimirvolek** [comment]
We currently have two wallets (mytrezor and next) in production, this repository is only for next wallet - https://beta-wallet.trezor.io/next/#/. Your issue is part of mytrezor so I moved your issue there.
