### ISSUE TITLE
Bitcoin fee estimation: Implement whatthefee.io

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-wallet#503]
Whatthefee.io by Felix Weis is using better algorithm than bitcoin core's "estimatesmartfee", because it consider not only the mempool, but also the dynamics of transactions actually getting into the chain. So the fees are more precise and usually significantly lower.

**Comment by slush0** [comment]
I'm currently asking Felix for API access and documentation. Also, we should not expect the service will be 100% stable, so there should be a fallback to estimatesmartfee in case of service outage.

**Comment by slush0** [comment]
```
$ curl https://whatthefee.io/data.json
{"index": [3, 6, 9, 12, 18, 24, 36, 48, 72, 96, 144], "columns": ["0.0500", "0.2000", "0.5000", "0.8000", "0.9500"], "data": [[60, 180, 280, 400, 440], [20, 120, 180, 380, 440], [0, 120, 160, 360, 420], [0, 80, 160, 300, 380], [0, 20, 120, 220, 360], [0, 20, 100, 180, 300], [0, 0, 80, 140, 240], [0, 0, 60, 100, 180], [0, 0, 40, 60, 140], [0, 0, 20, 20, 60], [0, 0, 0, 0, 20]]}
```

**Comment by martinboehm** [comment]
As discussed with @slush0, we will implement the functionality in Blockbook. There will be no change for wallet.
Closing here and taking it to https://github.com/trezor/blockbook/issues/153
