### ISSUE TITLE
Limit passphrase entry to 50 bytes

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-wallet#540]
Passphrase can have up to 50 bytes, which means either 50 ASCII characters, or less in case non-ASCII chars are used. Let's show an error in case it exceeds the 50 bytes.

**Comment by tsusanka** [comment]
Related to https://github.com/satoshilabs/mytrezor/issues/751 and https://github.com/satoshilabs/trezor-qa/issues/78

**Comment by slowbackspace** [comment]
https://github.com/satoshilabs/mytrezor/commit/3b089e973284dadc875de35854011eee986bfa90
