### ISSUE TITLE
Wallet shows connect Trezor when device is only Locked

### ISSUE THREAD

**Issue by TomasZorvan** [trezor/trezor-wallet#562]
From the UX point of view it would be nice for Trezor T to show `Unlock your device` if it is connected. 
![aaa](https://user-images.githubusercontent.com/7147101/57942811-b8c69c80-78d2-11e9-9006-9458dd46bd37.png)

**Comment by prusnak** [comment]
This is not possible, because the device has not opened the USB connection before the correct PIN is entered.
