### ISSUE TITLE
Coin Recovery

### ISSUE THREAD

**Issue by SFisherlmp** [trezor/trezor-wallet#572]
Accidently sent Trezor to LCC instead of LTC.

Is there a Coin Recovery for salvaging this please.

Thank You,
Sharon Fisher
vitalizingtouch@gmail.com
530-513-1714

**Comment by prusnak** [comment]
Contact support of the company that received the coins.

**Comment by SFisherlmp** [comment]
I am inquiring if Trezor has a Recovery for coins sent to a wrong address type of LCC instead of LTC  - similar to: 

https://trezor.io/recover-coins/

Thank You, Sharon
