### ISSUE TITLE
Wrong fee calculation

### ISSUE THREAD

**Issue by akbasemre1** [trezor/trezor-wallet#583]
Recently i realized my bitcoin transactions fees are lower than i set for sat/byte value looks like when you set fee HD wallet only calculates original transaction (I am not still sure about that) but there is a issue for sure. Can anyone test and confirm they experience that issue or not?

**Comment by vladimirvolek** [comment]
Hello @akbasemre1 
We will look into it. Thank you.

**Comment by pankrats** [comment]
> Recently i realized my bitcoin transactions fees are lower than i set for sat/byte value looks like when you set fee HD wallet only calculates original transaction (I am not still sure about that) but there is a issue for sure. Can anyone test and confirm they experience that issue or not?

Can you give us an example or reproduction steps, please? 
Are you talking about https://wallet.trezor.io/, where the issue occurs?

**Comment by akbasemre1** [comment]
@pankrats any transaction from non legacy account to any address with 1+ input and 1+ output (output is a must) create that issue for example this is my last transaction https://www.blockchain.com/btc/tx/83fa1f572aa294e83d11ea3386ea30f3ca9c252930d580e3b42354beca57a8f8 i tough it was a glitch happened one time when i first realize it but it's always happening wrote here. For that transaction I did input 6 sat/byte while transaction happened with  somewhere around 3 sat/byte.

I am talking about beta wallet beta-wallet.trezor.io since I was using trezor T I don't think I can use normal wallet.

**Comment by pankrats** [comment]
@akbasemre1 It is not a bug, it is a specific of Segwit transactions. 

For example, in your case, your tx was taken as a tx with 6 sat/B, but the real "price" was 3 sat/B, as SegWit tx are "cheaper". 
The information on this topic is widely available on-line, for instance, here: https://en.bitcoin.it/wiki/Techniques_to_reduce_transaction_fees#P2SH-wrapped_segwit

**Comment by akbasemre1** [comment]
@pankrats from what i understand segwit tx are cheaper because their size is lower than normal transactions so if i pay 1sat/byte for 100byte transaction on legacy when i used segwit byte will drop lets say 50 i will pay 50 but still that will be 1sat/byte while what happening is wallet calculate transaction is 50 byte and send transaction with 50 sat but transaction size is 100 byte so i pay 0.5sat per byte.  

Can you explain that what i understand is fee i paid is fixed and if segwit is cheaper from my calculation byte x sat = fee. Fee is fixed byte is dropped because segwit tx are "cheaper" so sat per byte should be 12 isn't it?

**Comment by ng2027** [comment]
> @pankrats any transaction from non legacy account to any address with 1+ input and 1+ output (output is a must) create that issue for example this is my last transaction https://www.blockchain.com/btc/tx/83fa1f572aa294e83d11ea3386ea30f3ca9c252930d580e3b42354beca57a8f8 i tough it was a glitch happened one time when i first realize it but it's always happening wrote here. For that transaction I did input 6 sat/byte while transaction happened with somewhere around 3 sat/byte.
> 
> I am talking about beta wallet beta-wallet.trezor.io since I was using trezor T I don't think I can use normal wallet.

this is also happening to me is there any fix?

**Comment by prusnak** [comment]
> this is also happening to me is there any fix?

Try using https://suite.trezor.io
