### ISSUE TITLE
Next wallet behavior with BTC only FW

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-wallet#608]
Please see screenshot and fix behaviour of Next wallet when user connects device with BTC only firmware.

![image](https://user-images.githubusercontent.com/31506317/63758418-07190d80-c8bc-11e9-9abb-4d2d81a65b09.png)

**Comment by bosomt** [comment]
you can even get receive address via sign and verify or via show transaction history 

![image](https://user-images.githubusercontent.com/31506317/64508632-311bf800-d2de-11e9-9132-c206a8a91cea.png)
![image](https://user-images.githubusercontent.com/31506317/64508659-41cc6e00-d2de-11e9-91e8-137a1d7cc130.png)

**Comment by sorooris** [comment]
**Issue:** Unhandled unexpected message when using BTC-only firmware device

Next wallet - **stage** (08826e1e85)
Any device with BTC-only firmware.

**Steps to reproduce:**
1. Navigate to the wallet with a BTC-only firmware device.
2. Enter passphrase if enabled and select a coin.
3. Observe.

**Expected:**
A warning message that the user is trying to access an altcoin wallet with BTC-only capable device is displayed.
**Actual:**
An error message "Account discovery error - Unexpected message" is displayed.
Also when compared to the Next wallet - beta, account discovery is run and the message ("Verifying address error - Unknown message") is displayed only after attempting to display a receiving address.

Note: tested with _1.9.0; 2.1.8, 2.3.0_ and _Connect 8.1_

**Screenshot:**
![image](https://user-images.githubusercontent.com/10185314/78909300-99ed6d80-7a83-11ea-855b-9d256ff99a16.png)

**Comment by bosomt** [comment]
Next wallet is obsolete and it will be replaced by beta wallet in upcoming weeks
