### ISSUE TITLE
Bech32 / Native Segwit Support still not in Web Wallet

### ISSUE THREAD

**Issue by maltokyo** [trezor/trezor-wallet#610]
It’s really a pain to have to load electrum and other alternatives for Bech32 addresses. 

We don’t understand why it takes you so long to support a feature that’s been in your hardware firmware for so long. 

Please let us know the plans for support and/or at least let us know why it takes so long!

**Comment by prusnak** [comment]
This feature will come soon. ETA Q4 this year.

**Comment by maltokyo** [comment]
Why do you close it. It’s still an open issue. Your software lacks support for your hardware. Can’t we leave it open until this issue for your users is resolved?

**Comment by prusnak** [comment]
We are tracking the issue here: https://github.com/trezor/trezor-suite/issues/231

**Comment by ybaidiuk** [comment]
@prusnak  Today is 2021, and you still not support bech32!

**Comment by maltokyo** [comment]
they do now, finally, in here https://suite.trezor.io/

**Comment by prusnak** [comment]
> @prusnak Today is 2021, and you still not support bech32!

Yes, Suite is our new wallet with Bech32 support by default - see https://suite.trezor.io and use that
