### ISSUE TITLE
Blind coin selection should spend lowest size UTXO first.

### ISSUE THREAD

**Issue by Transisto** [trezor/trezor-wallet#612]
Without any coin selection I think the conservative approach is to spend the smallest UTXO size as the transaction requires.

That's not how it work right now, most likely spending oldest coin first or something.

**Comment by prusnak** [comment]
Spending the oldest coins first have a nice property that it cleans up the older blocks of UTXOs. Moreover spending always the smallest UTXO first will create lots of unusable UTXOs because they will be very small to actually pay for anything.
