### ISSUE TITLE
Cannot run discovery for XRP

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-wallet#613]
![image](https://user-images.githubusercontent.com/3112191/67644942-ee61be00-f925-11e9-9005-bd9b17e218cf.png)

**Comment by prusnak** [comment]
Seems like Ripple changed their server APIs.

**Comment by prusnak** [comment]
It was Ripple libraries which were broken.

Fixed here: https://github.com/ripple/ripple-lib/pull/869
We are awaiting for the fix to be released: https://github.com/ripple/ripple-lib/issues/1066

Meanwhile we monkey-patch our code in Connect: https://github.com/trezor/connect/pull/482

**Comment by intelliot** [comment]
Should be fixed in ripple-lib@1.4.0

**Comment by szymonlesisz** [comment]
solved
