### ISSUE TITLE
Prevent accidental copying of non-xpub data

### ISSUE THREAD

**Issue by jlopp** [trezor/trezor-wallet#614]
I had someone report that my [extended public key converter tool](https://jlopp.github.io/xpub-converter/) wasn't working for Trezor ypubs. Upon closer inspection it appear that the issue is due to the fact that double clicking on the extended public key ALSO highlights the word "Account" on the right of the span.

I suspect that if you put the "Account #N" text into a different span, it will prevent it from being highlighted by a double click and will prevent future confusion for users.

`<span class="xpub-in ng-binding">ypubGoesHere</span>`

**Comment by prusnak** [comment]
Moved to internal tracker as this is a repo for next generation of the wallet, not the one currently deployed at wallet.trezor.io. Thanks for the report.
