### ISSUE TITLE
Cannot perform seed backup from Android browser

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-wallet#616]
Steps to reproduce

1. Install Android [Chrome Beta](https://play.google.com/store/apps/details?id=com.chrome.beta) v79.0.3945.18 since Android [Chrome](https://play.google.com/store/apps/details?id=com.android.chrome) is still broken in regards to WebUSB
2. Wipe your Trezor using `trezorctl wipe-device --bootloader` from a PC.
3. Browse to `beta-wallet.trezor.io` on Android in Chrome Beta
4. Connect your Trezor via USB OTG and proceed as prompted.
5. Note that the prompt to backup is nowhere in the workflow.

This same workflow fails if switching in between `beta-wallet.trezor.io` and `beta-wallet.trezor.io/next`

This workflow also fails whether or not **Desktop site** is enabled 

The [Trezor Manager](https://play.google.com/store/apps/details?id=io.trezor.app) app still works to perform the backup without issue, though it is currently [bugged when trying to flash firmware](https://github.com/trezor/trezor-android/issues/57)

**Comment by prusnak** [comment]
Closing the issue, because the wallet is being replaced with Trezor Suite.

Please open a new issue in the Trezor Suite repository if the issue still persists: https://github.com/trezor/trezor-suite
