### ISSUE TITLE
Cannot install & run locally (MacOS 10.14 and Ubuntu 16.04)

### ISSUE THREAD

**Issue by MIPPL** [trezor/trezor-wallet#618]
I am adapting the beta wallet to other altcoins. I downloaded the beta branch and followed the instructions but I can't get past npm install in both MacOS and Ubuntu

Environment 1: MacOS 10.14
$ npm -v
6.12.1
$ node -v
v13.5.0
$ yarn -v
1.21.1

npm install error log:
[2019-12-29T11_29_19_729Z-debug.log](https://github.com/trezor/trezor-wallet/files/4007995/2019-12-29T11_29_19_729Z-debug.log)

Environment 2: Ubuntu 16.04
$ npm -v
6.13.4
$ node -v
v13.5.0
$ yarn -v
1.21.1

npm install error log:
[2019-12-29T11_45_38_487Z-debug.log](https://github.com/trezor/trezor-wallet/files/4008006/2019-12-29T11_45_38_487Z-debug.log)

I am no expert in nodejs and I cannot fully understand those logs. It would be greatly appreciated if there was some sort of step-by-step "foolproof" install & locally run guide. 

Thank you very much in advance

**Comment by vladimirvolek** [comment]
Can you please try again with a node version around 10?

**Comment by MIPPL** [comment]
Wow that worked nicely. For MacOS I leave the steps I used:

\# remove previous node versions from brew cellar
$ brew uninstall --force yarn
$ brew uninstall --force node

Then install node version manager (nvm)  following https://michael-kuehnel.de/node.js/2015/09/08/using-vm-to-switch-node-versions.html

$ nvm install 10
$ nvm use 10

$ node -v
v10.18.0

\# reinstall yarn
$ brew install yarn

Then you can proceed with the instructions found in trezor-wallet readme (npm install / npm run dev / etc)

Thank you so much for the assistance
