### ISSUE TITLE
Wallet says Your device is in firmware update mode when there is no FW installed

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-wallet#621]
Wallet says Your device is in firmware update mode when there is no FW installed
It says Please re-connect it
But this won't help you to install FW.

![image](https://user-images.githubusercontent.com/31506317/71802490-1bd19300-305e-11ea-9cd0-e90e415ad370.png)

**Comment by prusnak** [comment]
Closing the issue because the wallet is being replaced with the Trezor Suite.

Please open a new issue in the Trezor Suite repository if the issue still persists: https://github.com/trezor/trezor-suite
