### ISSUE TITLE
Not able to scroll in wallet settings in mobile view

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-wallet#622]
Not able to scroll/close/save in wallet settings in mobile view.
Standard view works fine /same for more other parts of wallet in mobile view/

![image](https://user-images.githubusercontent.com/31506317/72409565-69d54d80-3766-11ea-8afc-d7f59d781d24.png)

**Comment by bosomt** [comment]
same behavior in stage and beta wallet
works fine when you go to wallet settings and then switch to mobile view
 
but when you are at mobile view and then you enter wallet settings then you cant scroll

**Comment by prusnak** [comment]
Closing the issue because the wallet is being replaced with the Trezor Suite.

Please open a new issue in the Trezor Suite repository if the issue still persists: https://github.com/trezor/trezor-suite
