### ISSUE TITLE
CSV export issue when commas are used in labeling 

### ISSUE THREAD

**Issue by victortrezor** [trezor/trezor-wallet#624]
Request for the CSV export feature to enclose the transaction labels "in double quotes", so it does not break down when someone uses commas in the labels. 

If there is already a double quote character in the string, it should be written twice like "a string with ""a quotation"" inside".

**Comment by prusnak** [comment]
Closing the issue because the wallet is being replaced with the Trezor Suite.

Please open a new issue in the Trezor Suite repository if the issue still persists: https://github.com/trezor/trezor-suite
