### ISSUE TITLE
Next Wallet does not allow add ERC20 token with already used name

### ISSUE THREAD

**Issue by cryptomar1o** [trezor/trezor-wallet#627]
When trying to add two different ERC-20 tokens (by their contract address) with the same token name, it says Already added.

Example:
SWARM with contract address 0x9e88613418cf03dca54d6a2cf6ad934a78c7a17a
SWARM with contract address 0x3505f494c3f0fed0b594e01fa41dd3967645ca39

Second example:
CAT with contract address 0x90A892Af2d05b5D1c498D336D307eA77A63b25d3
CAT with contract address 0x0396F609b8308ecD3cf94EceB7b6e12122455412

![01](https://user-images.githubusercontent.com/52966597/79796908-a496e500-8356-11ea-9e57-03d715f56f37.png)
![02](https://user-images.githubusercontent.com/52966597/79796917-a791d580-8356-11ea-9554-b19263299be4.png)

**Comment by bosomt** [comment]
tested and yes, you can't add token with different address but with same name

**Comment by prusnak** [comment]
Closing the issue because the wallet is being replaced with the Trezor Suite.

Please open a new issue in the Trezor Suite repository if the issue still persists: https://github.com/trezor/trezor-suite
