### ISSUE TITLE
Wrong balance shown for USDT

### ISSUE THREAD

**Issue by leshik** [trezor/trezor-wallet#628]
After sending USDT in beta-wallet, the resulting balance is displayed incorrectly:
![usdt](https://user-images.githubusercontent.com/443678/81025360-a1484100-8ea0-11ea-9c21-18eb00ec3085.png)
Forgetting device & refreshing the page fixes it.

PS: the screenshot shows the value of the transaction, which was 500 USDT in this case. The balance itself is also shown incorrectly with the deep negative value. Unfortunately, I don't have more screenshots as I don't use shitcoins and therefore can't reproduce it on my computer. Was helping a friend. :)

**Comment by prusnak** [comment]
Closing the issue, because the wallet is being replaced with Trezor Suite.

Please open a new issue in the Trezor Suite repository if the issue still persists: https://github.com/trezor/trezor-suite
