### ISSUE TITLE
Add multisig support to BCH?

### ISSUE THREAD

**Issue by vermorel** [trezor/trezor-wallet#634]
The web wallet of Trezor is fantastic. It would be really nice if multsig was supported for BCH. Multisig are an essential element of security whenever professional uses are involved. It would be a great addition to the Trezor Wallet.

Ps: I am presently [out-of-luck](https://github.com/Electron-Cash/Electron-Cash/issues/1961) as far Electron Cash is concerned.

**Comment by prusnak** [comment]
We are not adding multisig to the Trezor wallet for now.
