### ISSUE TITLE
Problems with sending Zcash (ZEC)

### ISSUE THREAD

**Issue by victortrezor** [trezor/trezor-wallet#635]
OS: Windows 10 pro version 1903
Bridge: 2.0.27 
FW: 2.3.2
Used backend: https://zec1.trezor.io/ 

Original error was: 
![image](https://user-images.githubusercontent.com/41474975/90537487-ab572c80-e17d-11ea-92ae-8870be23db06.png)

After using the link with a hotfix: https://beta-wallet.trezor.io/mytrezor/ he is currently facing the one below: 

![image](https://user-images.githubusercontent.com/41474975/90536979-0d636200-e17d-11ea-80e0-340104c9fa2b.png)

**Comment by prusnak** [comment]
Closing the issue, because the wallet is being replaced with Trezor Suite.

Please open a new issue in the Trezor Suite repository if the issue still persists: https://github.com/trezor/trezor-suite
