### ISSUE TITLE
SAI and DAI mixed up

### ISSUE THREAD

**Issue by Tomm-y** [trezor/trezor-wallet#636]
Dear community,

one of our customers pointed out that our beta wallet should be capable of receiving SAI and DAI while it actually is not. Now, I know that both are ERC20 tokens so technically, it is. However, when you search DAI, it finds only DAI stable coin v1.0., which by the name should be SAI. On top of that, when you look for SAI, there is nothing to be found. 

I'm therefore asking you to change DAI stable coin v1.0. to SAI and to add DAI stablecoin v2.0. as DAI in our beta wallet. Thank you in advance.

**Comment by prusnak** [comment]
Closing the issue because the wallet is being replaced with the Trezor Suite.

Please open a new issue in the Trezor Suite repository if the issue still persists: https://github.com/trezor/trezor-suite
